using System.Text.RegularExpressions;
using DataGuard.Core.Abstractions;
using DataGuard.Core.Rules;
using Microsoft.CodeAnalysis;

namespace DataGuard.PostgreSql.Adapter;

/// <summary>
/// PostgreSQL dialect checker — detects PostgreSQL-specific syntax in non-PostgreSQL
/// context and vice versa. Follows the OracleDialectChecker pattern.
/// </summary>
public sealed class PostgreSqlDialectChecker
{
    // Only genuinely PostgreSQL-specific. Standard SQL (window functions, CTEs,
    // LATERAL, MERGE) is valid in modern databases and must not be flagged.
    private static readonly HashSet<string> PostgreSqlKeywords = new(StringComparer.OrdinalIgnoreCase)
    {
        // Serial / identity variants
        "SERIAL", "BIGSERIAL", "SMALLSERIAL",

        // PostgreSQL-specific types
        "JSONB", "JSONPATH", "UUID", "CIDR", "INET", "MACADDR", "MACADDR8",
        "MONEY", "OID", "TID", "XID", "CID", "REGCLASS", "REGTYPE", "REGPROC",
        "REGOPERATOR", "REGCONFIG", "REGDICTIONARY", "TXID_SNAPSHOT",
        "INT4RANGE", "INT8RANGE", "NUMRANGE", "TSRANGE", "TSTZRANGE",
        "DATERANGE", "TSQUERY", "TSVECTOR",

        // ILIKE is PostgreSQL-only (MySQL has it too, but not SQL Server/Oracle)
        "ILIKE",

        // PostgreSQL functions
        "GENERATED ALWAYS AS IDENTITY",
        "GENERATED BY DEFAULT AS IDENTITY",
        "CITEXT",
        "HSTORE",
        "LTREE",
        "PG_SLEEP", "PG_TERMINATE_BACKEND", "PG_CANCEL_BACKEND",
        "PG_ADVISORY_LOCK", "PG_ADVISORY_UNLOCK",
        "CURRENT_SETTING", "SET_CONFIG",
        "STRING_AGG", "ARRAY_AGG", "JSON_AGG", "JSONB_AGG",
        "JSON_BUILD_OBJECT", "JSONB_BUILD_OBJECT",
        "JSON_OBJECT", "JSONB_OBJECT",
        "TO_JSON", "TO_JSONB", "JSONB_PRETTY",
        "XMLCONCAT", "XMLPI", "XMLROOT", "XMLCOMMENT",
        "UNNEST", "GENERATE_SERIES", "GENERATE_SUBSCRIPTS",
        "CROSSTAB", "NORMALIZE",
        "LISTEN", "NOTIFY",
    };

    private static readonly HashSet<string> PostgreSqlOperators = new(StringComparer.OrdinalIgnoreCase)
    {
        // :: handled by regex below (word-boundary match)
        "||",       // string concatenation (also Oracle, but not SQL Server)
        "~",        // POSIX regex match
        "~*",       // case-insensitive regex match
        "!~",       // negated regex match
        "!~*",      // negated case-insensitive regex match
        "@>",       // JSONB/Array containment
        "<@",       // JSONB/Array contained by
        "?",        // JSONB key existence
        "?|",       // JSONB any key existence
        "?&",       // JSONB all keys existence
        "#>",       // JSONB path extraction
        "#>>",      // JSONB path extraction as text
        "->",       // JSON field by key
        "->>",      // JSON field as text
        "#-",       // JSONB path delete
        "&&",       // array overlap / range overlap
        "-|-",      // range adjacency
    };

    // Non-PostgreSQL (SQL Server / MySQL / Oracle) keywords
    private static readonly HashSet<string> SqlServerKeywords = new(StringComparer.OrdinalIgnoreCase)
    {
        // SQL Server functions
        "ISNULL", "GETDATE", "GETUTCDATE", "DATEADD", "DATEDIFF",
        "DATEPART", "DATENAME", "DATETRUNC", "EOMONTH",
        "IDENTITY", "NEWID", "NEWSEQUENTIALID",
        "IIF", "CHOOSE", "FORMAT", "CONVERT", "TRY_CAST", "TRY_CONVERT", "TRY_PARSE",
        "SCOPE_IDENTITY", "@@IDENTITY", "IDENT_CURRENT",
        "TOP", "WITH(NOLOCK)", "NOLOCK",
        "EXEC ", "EXECUTE ",
        "SUSER_SNAME", "SUSER_NAME", "SYSTEM_USER",
        "APP_NAME", "HOST_NAME", "HOST_ID",
        "RAISERROR", "THROW",
        "REPLACE", // exists in PG too, but "REPLACE INTO" is MySQL
        "PIVOT", "UNPIVOT", // SQL Server specific syntax form
        "OPENQUERY", "OPENROWSET", "OPENDATASOURCE",
        "MERGE", // SQL Server MERGE syntax (PG 15+ has MERGE but different syntax)
        "OUTPUT", // SQL Server OUTPUT clause
        "CUBE", "ROLLUP", "GROUPING SETS", // exist in PG too, but GROUPING_ID is SQL Server
        "GROUPING_ID",
        "STRING_SPLIT", "STRING_ESCAPE",
        "JSON_VALUE", "JSON_QUERY", "JSON_MODIFY", "OPENJSON",
        "PARSENAME",
        "PATINDEX", "CHARINDEX", "DATALENGTH",
        "QUOTENAME",
        "SERVERPROPERTY", "DATABASEPROPERTYEX",
        "sp_executesql", "sp_who", "sp_lock",
        "DBCC",
        "PRINT",
        "WAITFOR",
        "GO", // batch separator
    };

    private static readonly HashSet<string> OracleKeywords = new(StringComparer.OrdinalIgnoreCase)
    {
        "DECODE", "NVL", "NVL2", "DUAL", "ROWNUM", "CONNECT BY", "START WITH",
        "SYSDATE", "SYSTIMESTAMP", "NEXTVAL", "CURRVAL", "ROWID",
        "LISTAGG", "WM_CONCAT",
        "REGEXP_LIKE", "REGEXP_REPLACE", "REGEXP_SUBSTR", "REGEXP_INSTR",
        "TO_CHAR", "TO_NUMBER", "TO_DATE", // Oracle-specific forms (PG has to_char but different syntax)
        "NVL2", "COALESCE", // COALESCE is standard, NVL2 is Oracle-only
        "SOUNDEX", // exists in PG too, but often an Oracle leak
        "UTL_FILE", "UTL_HTTP", "DBMS_OUTPUT", "DBMS_LOB",
        "BFILE", "LONG RAW", "RAW",
        "VARCHAR2", "NVARCHAR2", "NUMBER", // Oracle types
        "BINARY_INTEGER", "PLS_INTEGER",
    };

    private static readonly HashSet<string> MySqlKeywords = new(StringComparer.OrdinalIgnoreCase)
    {
        "IFNULL", "GROUP_CONCAT", "LIMIT", // LIMIT exists in PG too, but "LIMIT x, y" offset syntax is MySQL
        "AUTO_INCREMENT",
        "ENGINE=", "CHARSET=", "COLLATE=",
        "UNSIGNED", "ZEROFILL",
        "SHOW TABLES", "SHOW DATABASES", "SHOW COLUMNS",
        "DESCRIBE", // exists in PG too, but "DESCRIBE table" is MySQL style
        "REPLACE INTO",
        "INSERT IGNORE", "ON DUPLICATE KEY UPDATE",
        "LOCK TABLES", "UNLOCK TABLES",
        "LOAD_FILE",
        "REGEXP", // MySQL REGEXP (PG uses ~ or ~*)
        "RLIKE",
        "SLEEP",
        "FOUND_ROWS", "ROW_COUNT",
        "CONV", "ELT", "EXPORT_SET", "FIELD", "FIND_IN_SET",
        "FORMAT", // MySQL FORMAT() function
        "INET_ATON", "INET_NTOA",
        "UUID_SHORT",
    };

    /// <summary>
    /// Checks for PostgreSQL syntax in non-PostgreSQL context.
    /// </summary>
    public IReadOnlyList<ContractViolation> CheckPostgreSqlSyntaxInNonPostgreSqlContext(
        string sqlText,
        bool isPostgreSqlContext,
        Location? location = null)
    {
        if (string.IsNullOrEmpty(sqlText))
        {
            return Array.Empty<ContractViolation>();
        }

        if (isPostgreSqlContext)
        {
            return Array.Empty<ContractViolation>();
        }

        var violations = new List<ContractViolation>();

        // Check PostgreSQL-specific keywords
        foreach (var keyword in PostgreSqlKeywords)
        {
            if (ContainsKeyword(sqlText, keyword))
            {
                violations.Add(new ContractViolation(
                    "PG001",
                    $"PostgreSQL-specific keyword '{keyword}' used in non-PostgreSQL context",
                    DiagnosticSeverity.Warning,
                    location,
                    new Dictionary<string, object?> { { "keyword", keyword } }));
            }
        }

        // Check PostgreSQL-specific operators (substring match)
        foreach (var op in PostgreSqlOperators)
        {
            if (sqlText.Contains(op, StringComparison.OrdinalIgnoreCase))
            {
                violations.Add(new ContractViolation(
                    "PG001",
                    $"PostgreSQL-specific operator '{op}' used in non-PostgreSQL context",
                    DiagnosticSeverity.Warning,
                    location,
                    new Dictionary<string, object?> { { "operator", op } }));
            }
        }

        // Check :: type cast syntax (very PostgreSQL-specific)
        if (Regex.IsMatch(sqlText, @"::\w+", RegexOptions.IgnoreCase))
        {
            violations.Add(new ContractViolation(
                "PG001",
                "PostgreSQL type cast operator '::' used in non-PostgreSQL context",
                DiagnosticSeverity.Warning,
                location,
                new Dictionary<string, object?> { { "operator", "::" } }));
        }

        return violations;
    }

    /// <summary>
    /// Checks for non-PostgreSQL syntax in PostgreSQL context.
    /// </summary>
    public IReadOnlyList<ContractViolation> CheckNonPostgreSqlSyntaxInPostgreSqlContext(
        string sqlText,
        bool isPostgreSqlContext,
        Location? location = null)
    {
        if (string.IsNullOrEmpty(sqlText))
        {
            return Array.Empty<ContractViolation>();
        }

        if (!isPostgreSqlContext)
        {
            return Array.Empty<ContractViolation>();
        }

        var violations = new List<ContractViolation>();

        // Check SQL Server keywords
        foreach (var keyword in SqlServerKeywords)
        {
            if (ContainsKeyword(sqlText, keyword))
            {
                violations.Add(new ContractViolation(
                    "PG002",
                    $"SQL Server-specific keyword '{keyword}' used in PostgreSQL context",
                    DiagnosticSeverity.Warning,
                    location,
                    new Dictionary<string, object?>
                    {
                        { "keyword", keyword },
                        { "source", "SqlServer" },
                    }));
            }
        }

        // Check Oracle keywords
        foreach (var keyword in OracleKeywords)
        {
            if (ContainsKeyword(sqlText, keyword))
            {
                violations.Add(new ContractViolation(
                    "PG002",
                    $"Oracle-specific keyword '{keyword}' used in PostgreSQL context",
                    DiagnosticSeverity.Warning,
                    location,
                    new Dictionary<string, object?>
                    {
                        { "keyword", keyword },
                        { "source", "Oracle" },
                    }));
            }
        }

        // Check MySQL keywords
        foreach (var keyword in MySqlKeywords)
        {
            if (ContainsKeyword(sqlText, keyword))
            {
                violations.Add(new ContractViolation(
                    "PG002",
                    $"MySQL-specific keyword '{keyword}' used in PostgreSQL context",
                    DiagnosticSeverity.Warning,
                    location,
                    new Dictionary<string, object?>
                    {
                        { "keyword", keyword },
                        { "source", "MySql" },
                    }));
            }
        }

        // Check SQL Server TOP clause (word-boundary: TOP n, not TOPIC)
        if (Regex.IsMatch(sqlText, @"\bTOP\s+\d+", RegexOptions.IgnoreCase))
        {
            violations.Add(new ContractViolation(
                "PG002",
                "SQL Server TOP clause used in PostgreSQL context (use LIMIT n)",
                DiagnosticSeverity.Warning,
                location,
                new Dictionary<string, object?> { { "suggestion", "LIMIT" } }));
        }

        // Check SQL Server EXEC dbo.Procedure syntax
        if (Regex.IsMatch(sqlText, @"\bEXEC\s+\w+\.", RegexOptions.IgnoreCase))
        {
            violations.Add(new ContractViolation(
                "PG002",
                "SQL Server EXEC dbo.Procedure syntax used in PostgreSQL context. Use CALL or SELECT.",
                DiagnosticSeverity.Warning,
                location,
                new Dictionary<string, object?> { { "suggestion", "CALL" } }));
        }

        // Check MySQL LIMIT offset, count syntax (dual-arg LIMIT)
        if (Regex.IsMatch(sqlText, @"\bLIMIT\s+\d+\s*,\s*\d+", RegexOptions.IgnoreCase))
        {
            violations.Add(new ContractViolation(
                "PG002",
                "MySQL-style 'LIMIT offset, count' used in PostgreSQL context. Use 'LIMIT count OFFSET offset'.",
                DiagnosticSeverity.Warning,
                location,
                new Dictionary<string, object?> { { "suggestion", "LIMIT count OFFSET offset" } }));
        }

        // Check Oracle NVL (PostgreSQL uses COALESCE)
        if (Regex.IsMatch(sqlText, @"\bNVL\s*\(", RegexOptions.IgnoreCase))
        {
            violations.Add(new ContractViolation(
                "PG002",
                "Oracle NVL() used in PostgreSQL context. Use COALESCE() instead.",
                DiagnosticSeverity.Warning,
                location,
                new Dictionary<string, object?> { { "suggestion", "COALESCE" } }));
        }

        // Check Oracle DECODE (PostgreSQL uses CASE WHEN)
        if (Regex.IsMatch(sqlText, @"\bDECODE\s*\(", RegexOptions.IgnoreCase))
        {
            violations.Add(new ContractViolation(
                "PG002",
                "Oracle DECODE() used in PostgreSQL context. Use CASE WHEN instead.",
                DiagnosticSeverity.Warning,
                location,
                new Dictionary<string, object?> { { "suggestion", "CASE WHEN" } }));
        }

        // Check ISNULL (SQL Server; PostgreSQL uses COALESCE)
        if (Regex.IsMatch(sqlText, @"\bISNULL\s*\(", RegexOptions.IgnoreCase))
        {
            violations.Add(new ContractViolation(
                "PG002",
                "SQL Server ISNULL() used in PostgreSQL context. Use COALESCE() instead.",
                DiagnosticSeverity.Warning,
                location,
                new Dictionary<string, object?> { { "suggestion", "COALESCE" } }));
        }

        // Check GETDATE() (SQL Server; PostgreSQL uses NOW() or CURRENT_TIMESTAMP)
        if (Regex.IsMatch(sqlText, @"\bGETDATE\s*\(\s*\)", RegexOptions.IgnoreCase))
        {
            violations.Add(new ContractViolation(
                "PG002",
                "SQL Server GETDATE() used in PostgreSQL context. Use NOW() or CURRENT_TIMESTAMP.",
                DiagnosticSeverity.Warning,
                location,
                new Dictionary<string, object?> { { "suggestion", "NOW()" } }));
        }

        // Check IDENTITY column syntax (SQL Server; PostgreSQL uses GENERATED ALWAYS AS IDENTITY or SERIAL)
        if (Regex.IsMatch(sqlText, @"\bIDENTITY\s*\(", RegexOptions.IgnoreCase))
        {
            violations.Add(new ContractViolation(
                "PG002",
                "SQL Server IDENTITY() used in PostgreSQL context. Use GENERATED ALWAYS AS IDENTITY or SERIAL.",
                DiagnosticSeverity.Warning,
                location,
                new Dictionary<string, object?> { { "suggestion", "GENERATED ALWAYS AS IDENTITY" } }));
        }

        return violations;
    }

    /// <summary>
    /// Checks for provider option mismatch.
    /// </summary>
    public IReadOnlyList<ContractViolation> CheckProviderOptionMismatch(
        bool isPostgreSqlContext,
        string providerName,
        Location? location = null)
    {
        if (isPostgreSqlContext && !providerName.Contains("Npgsql", StringComparison.OrdinalIgnoreCase)
            && !providerName.Contains("PostgreSql", StringComparison.OrdinalIgnoreCase))
        {
            return new List<ContractViolation>
            {
                new ContractViolation(
                    "PG004",
                    $"PostgreSQL context detected but provider is '{providerName}'. Expected Npgsql provider.",
                    DiagnosticSeverity.Error,
                    location),
            };
        }

        return Array.Empty<ContractViolation>();
    }

    /// <summary>
    /// Checks for unmapped type usage in raw SQL for Npgsql EF Core provider.
    /// </summary>
    public IReadOnlyList<ContractViolation> CheckRawSqlUnmappedTypeUsage(
        string sqlText,
        bool isPostgreSqlContext,
        Location? location = null)
    {
        var violations = new List<ContractViolation>();

        if (!isPostgreSqlContext)
        {
            return violations;
        }

        // SQL Server types that Npgsql EF Core does not map
        string[] sqlServerTypes =
        {
            "UNIQUEIDENTIFIER", "MONEY", "SMALLMONEY", "DATETIME2", "DATETIMEOFFSET",
            "GEOGRAPHY", "GEOMETRY", "HIERARCHYID", "SQL_VARIANT",
            "TINYINT", "IMAGE", "NTEXT", "SMALLDATETIME",
        };

        foreach (var type in sqlServerTypes)
        {
            if (ContainsKeyword(sqlText, type))
            {
                violations.Add(new ContractViolation(
                    "PG005",
                    $"Type '{type}' used with PostgreSQL EF Core raw SQL but not mapped by Npgsql provider",
                    DiagnosticSeverity.Warning,
                    location,
                    new Dictionary<string, object?> { { "type", type } }));
            }
        }

        // Oracle types that are not valid in PostgreSQL
        string[] oracleTypes =
        {
            "VARCHAR2", "NVARCHAR2", "NUMBER", "BINARY_FLOAT", "BINARY_DOUBLE",
            "CLOB", "NCLOB", "BLOB", "RAW", "ROWID", "BFILE",
        };

        foreach (var type in oracleTypes)
        {
            if (ContainsKeyword(sqlText, type))
            {
                violations.Add(new ContractViolation(
                    "PG005",
                    $"Oracle type '{type}' used in PostgreSQL context — not a valid PostgreSQL type",
                    DiagnosticSeverity.Warning,
                    location,
                    new Dictionary<string, object?> { { "type", type }, { "source", "Oracle" } }));
            }
        }

        return violations;
    }

    private static bool ContainsKeyword(string text, string keyword)
    {
        // Use word boundaries to avoid partial matches.
        // For multi-word keywords (e.g. "CONNECT BY"), use substring match.
        if (keyword.Contains(' '))
        {
            return text.Contains(keyword, StringComparison.OrdinalIgnoreCase);
        }

        var pattern = $@"\b{Regex.Escape(keyword)}\b";
        return Regex.IsMatch(text, pattern, RegexOptions.IgnoreCase);
    }
}

// ── ContractRuleBase rules ─────────────────────────────────────────────────

/// <summary>
/// Rule PG001: PostgreSQL syntax in non-PostgreSQL context.
/// </summary>
public class PostgreSqlSyntaxInNonPostgreSqlContextRule : ContractRuleBase
{
    public override string RuleId => "PG001";

    public override string Name => "PostgreSQL Syntax in Non-PostgreSQL Context";

    public override DiagnosticSeverity Severity => DiagnosticSeverity.Warning;

    public override string Description => "PostgreSQL-specific syntax detected in non-PostgreSQL context";

    protected override Task ValidateCoreAsync(
        ContractDescriptor contract,
        IReadOnlyList<ContractDescriptor> allContracts,
        List<ContractViolation> violations,
        CancellationToken cancellationToken)
    {
        if (contract is RawSqlDescriptor rawSql)
        {
            var checker = new PostgreSqlDialectChecker();
            violations.AddRange(checker.CheckPostgreSqlSyntaxInNonPostgreSqlContext(
                rawSql.SqlText, false, contract.Location));
        }

        return Task.CompletedTask;
    }
}

/// <summary>
/// Rule PG002: Non-PostgreSQL syntax in PostgreSQL context.
/// </summary>
public class NonPostgreSqlSyntaxInPostgreSqlContextRule : ContractRuleBase
{
    public override string RuleId => "PG002";

    public override string Name => "Non-PostgreSQL Syntax in PostgreSQL Context";

    public override DiagnosticSeverity Severity => DiagnosticSeverity.Warning;

    public override string Description => "Non-PostgreSQL syntax (SQL Server/Oracle/MySQL) detected in PostgreSQL context";

    protected override Task ValidateCoreAsync(
        ContractDescriptor contract,
        IReadOnlyList<ContractDescriptor> allContracts,
        List<ContractViolation> violations,
        CancellationToken cancellationToken)
    {
        if (contract is RawSqlDescriptor rawSql)
        {
            var checker = new PostgreSqlDialectChecker();
            violations.AddRange(checker.CheckNonPostgreSqlSyntaxInPostgreSqlContext(
                rawSql.SqlText, true, contract.Location));
        }

        return Task.CompletedTask;
    }
}

/// <summary>
/// Rule PG004: Provider option mismatch.
/// </summary>
public class PostgreSqlProviderOptionMismatchRule : ContractRuleBase
{
    public override string RuleId => "PG004";

    public override string Name => "PostgreSQL Provider Option Mismatch";

    public override DiagnosticSeverity Severity => DiagnosticSeverity.Error;

    public override string Description => "Database context doesn't match configured PostgreSQL provider";

    protected override Task ValidateCoreAsync(
        ContractDescriptor contract,
        IReadOnlyList<ContractDescriptor> allContracts,
        List<ContractViolation> violations,
        CancellationToken cancellationToken)
    {
        // Requires DbContext provider registration info (available only in the Roslyn analyzer).
        return Task.CompletedTask;
    }
}

/// <summary>
/// Rule PG005: Raw SQL unmapped type usage.
/// </summary>
public class PostgreSqlRawSqlUnmappedTypeUsageRule : ContractRuleBase
{
    public override string RuleId => "PG005";

    public override string Name => "PostgreSQL Raw SQL Unmapped Type Usage";

    public override DiagnosticSeverity Severity => DiagnosticSeverity.Warning;

    public override string Description => "Raw SQL uses type not mapped by Npgsql EF Core provider";

    protected override Task ValidateCoreAsync(
        ContractDescriptor contract,
        IReadOnlyList<ContractDescriptor> allContracts,
        List<ContractViolation> violations,
        CancellationToken cancellationToken)
    {
        if (contract is RawSqlDescriptor rawSql)
        {
            var checker = new PostgreSqlDialectChecker();
            violations.AddRange(checker.CheckRawSqlUnmappedTypeUsage(
                rawSql.SqlText, true, contract.Location));
        }

        return Task.CompletedTask;
    }
}

/// <summary>
/// Backward-compatible alias for PostgreSqlSyntaxInNonPostgreSqlContextRule.
/// Used by CLI and tests with the original class name.
/// </summary>
public class PostgreSqlSyntaxRule : PostgreSqlSyntaxInNonPostgreSqlContextRule
{
}

/// <summary>
/// Backward-compatible alias for NonPostgreSqlSyntaxInPostgreSqlContextRule.
/// Used by CLI and tests with the original class name.
/// </summary>
public class NonPostgreSqlSyntaxRule : NonPostgreSqlSyntaxInPostgreSqlContextRule
{
}
