<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>DataGuard.VisualStudio</AssemblyName>
    <RootNamespace>DataGuard.VisualStudio</RootNamespace>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>true</IncludeDebugSymbolsInVSIXContainer>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="17.14.2142" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="source.extension.vsixmanifest" />
    <None Include="LICENSE.txt" IncludeInVSIXContainer="true" />
    <AdditionalFiles Include="stylecop.json" />
    <VSCTCompile Include="Commands\DataGuard.vsct" />
  </ItemGroup>
</Project>
