<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PackageId>DataGuard.Cli</PackageId>
    <Authors>DataGuard Contributors</Authors>
    <Description>DataGuard CLI tool for contract validation.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dataguard</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataGuard.Core\DataGuard.Core.csproj" />
    <ProjectReference Include="..\DataGuard.SqlServer.Adapter\DataGuard.SqlServer.Adapter.csproj" />
    <ProjectReference Include="..\DataGuard.Oracle.Adapter\DataGuard.Oracle.Adapter.csproj" />
    <ProjectReference Include="..\DataGuard.MySql.Adapter\DataGuard.MySql.Adapter.csproj" />
    <ProjectReference Include="..\DataGuard.PostgreSql.Adapter\DataGuard.PostgreSql.Adapter.csproj" />
    <ProjectReference Include="..\DataGuard.Analyzers\DataGuard.Analyzers.csproj" />
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
      </ItemGroup>
</Project>