apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - rbac.yaml
  - agent.yaml
  - gateway.yaml
  - network-policy.yaml
  - pdb-hpa.yaml

configMapGenerator:
  - name: observability-collector-agent-config
    files:
      - agent.yaml=config/agent.yaml
  - name: observability-collector-gateway-config
    files:
      - gateway.yaml=config/gateway.yaml

generatorOptions:
  disableNameSuffixHash: true
