// <auto-generated/>
// This file contains both IDE (light) and CI (heavy) analyzers.
// The IDE layer uses IIncrementalGenerator for syntax-only, fast analysis.
// The CI layer uses full semantic analysis with database connection.

#nullable enable annotations

using System;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Operations;
using DataGuard.Contracts;

namespace DataGuard.Analyzers;

/// <summary>
/// Diagnostic IDs for DataGuard contract validation.
/// </summary>
public static class DiagnosticIds
{
    /// <summary>Diagnostic ID for an SQL call lacking DataGuard validation.</summary>
    public const string UnvalidatedSqlCall = "DG001";       // IDE light: marks unvalidated SQL calls
    /// <summary>Diagnostic ID for stored-procedure parameter mismatch.</summary>
    public const string ParameterMismatch = "DG002";         // CI heavy: parameter count/type mismatch
    /// <summary>Diagnostic ID for stored-procedure parameter direction mismatch.</summary>
    public const string DirectionMismatch = "DG003";         // CI heavy: IN/OUT/INOUT direction mismatch
    /// <summary>Diagnostic ID for result-set column-shape mismatch.</summary>
    public const string ColumnShapeMismatch = "DG004";       // CI heavy: result set column mismatch
    /// <summary>Diagnostic ID for nullable contract mismatch.</summary>
    public const string NullableMismatch = "DG005";          // CI heavy: nullable mismatch
    /// <summary>Diagnostic ID for naming-convention mismatch.</summary>
    public const string NamingConvention = "DG006";          // CI heavy: naming convention violation
    /// <summary>Diagnostic ID for entity length exceeding database column length.</summary>
    public const string LengthExceedsColumn = "DG007";       // CI heavy: entity length > column length
    /// <summary>Diagnostic ID for byte-semantics length overflow.</summary>
    public const string ByteLengthOverflow = "DG008";        // CI heavy: byte semantics overflow risk
    /// <summary>Diagnostic ID for inferred database-size fallback.</summary>
    public const string InferredSizeFallback = "DG009";      // CI heavy: NVARCHAR2(2000) fallback risk
    /// <summary>Diagnostic ID for Oracle syntax used outside Oracle.</summary>
    public const string OracleSyntaxInNonOracle = "DG010";   // CI heavy: Oracle syntax in non-Oracle context
    /// <summary>Diagnostic ID for non-Oracle function used in Oracle.</summary>
    public const string NonOracleFunctionInOracle = "DG011"; // CI heavy: SQL Server syntax in Oracle
    /// <summary>Diagnostic ID for provider option mismatch.</summary>
    public const string ProviderOptionMismatch = "DG012";    // CI heavy: missing UseOracle
    /// <summary>Diagnostic ID for SQL Server syntax leaking into Oracle.</summary>
    public const string SqlServerSyntaxLeak = "DG013";       // CI heavy: EXEC dbo. in Oracle
    /// <summary>Diagnostic ID for unsupported type usage.</summary>
    public const string UnmappedTypeUsage = "DG014";         // CI heavy: unmapped type in Oracle
    /// <summary>Diagnostic ID for a referenced table absent from schema.</summary>
    public const string PhantomTable = "DG015";              // CI heavy: table reference doesn't exist
    /// <summary>Diagnostic ID for a referenced column absent from schema.</summary>
    public const string PhantomColumn = "DG016";             // CI heavy: column reference doesn't exist
    /// <summary>Diagnostic ID for a SELECT statement without a FROM clause.</summary>
    public const string MissingFromClause = "DG098";         // CI heavy: SELECT without FROM clause
    /// <summary>Diagnostic ID for a potential SQL injection pattern.</summary>
    public const string SqlInjectionPattern = "DG099";       // CI heavy: potential SQL injection pattern
}

/// <summary>
/// Shared diagnostic descriptors for both IDE and CI layers.
/// </summary>
internal static class DiagnosticDescriptors
{
    // IDE Light Layer - Syntax only, very fast
    public static readonly DiagnosticDescriptor UnvalidatedSqlCall = new (
        id: DiagnosticIds.UnvalidatedSqlCall,
        title: "SQL call not validated",
        messageFormat: "SQL call '{0}' not validated - run 'dataguard check' for full validation",
        category: "DataGuard.IDE",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Marks SQL calls that haven't been validated against database schema. Run full validation in CI.");

    // CI Heavy Layer - Full semantic validation
    public static readonly DiagnosticDescriptor ParameterMismatch = new (
        id: DiagnosticIds.ParameterMismatch,
        title: "Parameter count/type mismatch",
        messageFormat: "{0}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Stored procedure parameter count or type doesn't match call site.");

    public static readonly DiagnosticDescriptor DirectionMismatch = new (
        id: DiagnosticIds.DirectionMismatch,
        title: "Parameter direction mismatch",
        messageFormat: "{0}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Parameter IN/OUT/INOUT direction doesn't match C# out/ref modifiers.");

    public static readonly DiagnosticDescriptor ColumnShapeMismatch = new (
        id: DiagnosticIds.ColumnShapeMismatch,
        title: "Result set column shape mismatch",
        messageFormat: "{0}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Stored procedure result set doesn't match entity properties.");

    public static readonly DiagnosticDescriptor NullableMismatch = new (
        id: DiagnosticIds.NullableMismatch,
        title: "Nullable mismatch",
        messageFormat: "{0}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Database column nullability doesn't match entity property.");

    public static readonly DiagnosticDescriptor NamingConvention = new (
        id: DiagnosticIds.NamingConvention,
        title: "Naming convention violation",
        messageFormat: "{0}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Column/property naming convention mismatch (snake_case vs PascalCase).");

    public static readonly DiagnosticDescriptor LengthExceedsColumn = new (
        id: DiagnosticIds.LengthExceedsColumn,
        title: "Entity length exceeds column length",
        messageFormat: "{0}",
        category: "DataGuard.Length",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Entity property max length exceeds database column length - truncation risk.");

    public static readonly DiagnosticDescriptor ByteLengthOverflow = new (
        id: DiagnosticIds.ByteLengthOverflow,
        title: "Byte length overflow risk",
        messageFormat: "{0}",
        category: "DataGuard.Length",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Unicode data may exceed column byte capacity in BYTE length semantics.");

    public static readonly DiagnosticDescriptor InferredSizeFallback = new (
        id: DiagnosticIds.InferredSizeFallback,
        title: "Inferred size fallback risk",
        messageFormat: "{0}",
        category: "DataGuard.Length",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "EF Core Oracle provider falls back to NVARCHAR2(2000) when size is null and Unicode=true.");

    public static readonly DiagnosticDescriptor OracleSyntaxInNonOracle = new (
        id: DiagnosticIds.OracleSyntaxInNonOracle,
        title: "Oracle syntax in non-Oracle context",
        messageFormat: "{0}",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Oracle-specific syntax (DECODE, NVL, (+), DUAL, etc.) used in non-Oracle context.");

    public static readonly DiagnosticDescriptor NonOracleFunctionInOracle = new (
        id: DiagnosticIds.NonOracleFunctionInOracle,
        title: "Non-Oracle function in Oracle context",
        messageFormat: "{0}",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "SQL Server functions (ISNULL, TOP, GETDATE) used in Oracle context.");

    public static readonly DiagnosticDescriptor ProviderOptionMismatch = new (
        id: DiagnosticIds.ProviderOptionMismatch,
        title: "Provider option mismatch",
        messageFormat: "{0}",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Oracle metadata reader requires UseOracle in DbContextOptions.");

    public static readonly DiagnosticDescriptor SqlServerSyntaxLeak = new (
        id: DiagnosticIds.SqlServerSyntaxLeak,
        title: "SQL Server syntax in Oracle",
        messageFormat: "{0}",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "SQL Server EXEC dbo.Proc syntax leaked into Oracle code.");

    public static readonly DiagnosticDescriptor UnmappedTypeUsage = new (
        id: DiagnosticIds.UnmappedTypeUsage,
        title: "Unmapped type usage",
        messageFormat: "{0}",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Oracle EF Core 8+ raw SQL requires mapped types.");
    public static readonly DiagnosticDescriptor PhantomTable = new (
        id: DiagnosticIds.PhantomTable,
        title: "Phantom table reference",
        messageFormat: "{0}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Raw SQL references a table that doesn't exist in the database schema (AI hallucination).");

    public static readonly DiagnosticDescriptor PhantomColumn = new (
        id: DiagnosticIds.PhantomColumn,
        title: "Phantom column reference",
        messageFormat: "{0}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Raw SQL references a column that doesn't exist in its table (AI hallucination).");

    public static readonly DiagnosticDescriptor MissingFromClause = new (
        id: DiagnosticIds.MissingFromClause,
        title: "Raw SQL query missing FROM clause",
        messageFormat: "{0}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Raw SQL SELECT query is missing a FROM clause.");

    public static readonly DiagnosticDescriptor SqlInjectionPattern = new (
        id: DiagnosticIds.SqlInjectionPattern,
        title: "Potential SQL injection pattern",
        messageFormat: "{0}",
        category: "DataGuard.Security",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Raw SQL contains a pattern that may indicate SQL injection.");
}

/// <summary>
/// IDE Light Layer: Incremental generator that marks unvalidated SQL calls with syntax-only analysis.
/// This runs on every keystroke and must be extremely fast (~ms).
/// Optimized for zero-allocation, minimal GC pressure, and incremental caching.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class UnvalidatedSqlCallGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Descriptor = DiagnosticDescriptors.UnvalidatedSqlCall;

    // Pre-computed method name sets for fast lookup (no allocation)
    private static readonly HashSet<string> EfCoreMethods = new (StringComparer.Ordinal)
    {
        "FromSqlRaw", "FromSqlInterpolated"
    };

    private static readonly HashSet<string> ExecuteSqlMethods = new (StringComparer.Ordinal)
    {
        "ExecuteSqlRaw", "ExecuteSqlRawAsync", 
        "ExecuteSqlInterpolated", "ExecuteSqlInterpolatedAsync"
    };

    // SQL keywords for fast literal detection
    private static readonly string[] SqlKeywords = 
    {
        "SELECT", "INSERT", "UPDATE", "DELETE", "EXEC", "BEGIN", "WITH", "MERGE"
    };

    /// <summary>
    /// Initializes the incremental syntax pipeline for unvalidated SQL call diagnostics.
    /// </summary>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Single provider that identifies all SQL call sites in one pass
        // Uses syntax-only predicates for maximum speed
        var sqlCalls = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPotentialSqlCall(node),
                transform: static (ctx, _) => ExtractSqlCallSite(ctx))
            .Where(static site => site != null)!;

        // Direct emission - no intermediate aggregation, no allocations
        context.RegisterSourceOutput(sqlCalls, static (ctx, site) => 
        {
            if (site != null)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    Descriptor,
                    site.Value.Location,
                    site.Value.MethodName));
            }
        });
    }

    /// <summary>
    /// Ultra-fast syntax-only predicate - no allocations, no string operations
    /// </summary>
    internal static bool HasDataGuardMarkerComment(SyntaxNode node)
    {
        // Quick-fixes emit "// DataGuard: ..." notes; a marker comment on the
        // enclosing statement suppresses the diagnostic (the dev acknowledged it).
        var statement = node.FirstAncestorOrSelf<StatementSyntax>() ?? node;
        foreach (var trivia in statement.GetLeadingTrivia())
        {
            if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) &&
                trivia.ToString().IndexOf("DataGuard:", StringComparison.Ordinal) >= 0)
            {
                return true;
            }
        }
        return false;
    }

    private static bool IsPotentialSqlCall(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax invocation)
            return false;

        // Fast path: check method name first (most common filter)
        if (HasDataGuardMarkerComment(invocation))
            return false;
        if (invocation.Expression is not MemberAccessExpressionSyntax memberAccess)
            return false;

        var methodName = memberAccess.Name.Identifier.ValueText;

        // Check against pre-computed sets - O(1) lookup
        if (EfCoreMethods.Contains(methodName) || ExecuteSqlMethods.Contains(methodName))
            return true;

        // Dapper methods - check prefix (slightly slower but rare)
        if (methodName.StartsWith("Query", StringComparison.Ordinal) ||
            methodName.StartsWith("Execute", StringComparison.Ordinal))
            return true;

        // Raw SQL detection - only if first arg is string literal
        var firstArg = invocation.ArgumentList.Arguments.FirstOrDefault();
        return firstArg?.Expression is LiteralExpressionSyntax lit && 
               lit.Token.Value is string str && 
               ContainsSqlKeyword(str);
    }

    private static bool ContainsSqlKeyword(ReadOnlySpan<char> text)
    {
        // Fast path: check common SQL keywords without allocation
        for (int i = 0; i < SqlKeywords.Length; i++)
        {
            if (text.Contains(SqlKeywords[i].AsSpan(), StringComparison.OrdinalIgnoreCase))
                return true;
        }
        return false;
    }

    /// <summary>
    /// Extracts minimal call site info - zero allocation when possible
    /// </summary>
    private static SqlCallSite? ExtractSqlCallSite(GeneratorSyntaxContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var memberAccess = (MemberAccessExpressionSyntax)invocation.Expression;
        var methodName = memberAccess.Name.Identifier.ValueText;

        // Determine call type from method name (fast path)
        var callType = GetCallType(methodName);

        // Skip if not a recognized SQL method
        if (callType == SqlCallType.Unknown)
            return null;

        // Extract SQL text only for literal/interpolated strings (cheap)
        var sqlText = ExtractSqlTextFast(invocation);
        if (string.IsNullOrEmpty(sqlText) && callType != SqlCallType.Dapper)
            return null; // No SQL text, likely not a real SQL call

        // Get containing type name only for EF Core (needed for diagnostics)
        string containingType = "";
        if (callType == SqlCallType.EfCore)
        {
            var symbolInfo = context.SemanticModel.GetSymbolInfo(memberAccess.Expression, CancellationToken.None);
            if (symbolInfo.Symbol is IMethodSymbol method && 
                method.ContainingType?.Name.StartsWith("DbSet", StringComparison.Ordinal) == true)
            {
                containingType = method.ContainingType.ToDisplayString();
            }
            else
            {
                return null; // Not on DbSet<T>
            }
        }

        return new SqlCallSite(methodName, invocation.GetLocation(), sqlText, containingType, callType);
    }

    private static SqlCallType GetCallType(string methodName)
    {
        if (EfCoreMethods.Contains(methodName)) return SqlCallType.EfCore;
        if (ExecuteSqlMethods.Contains(methodName)) return SqlCallType.ExecuteSql;
        if (methodName.StartsWith("Query", StringComparison.Ordinal) || 
            methodName.StartsWith("Execute", StringComparison.Ordinal)) 
            return SqlCallType.Dapper;
        return SqlCallType.Unknown;
    }

    private static string ExtractSqlTextFast(InvocationExpressionSyntax invocation)
    {
        var firstArg = invocation.ArgumentList.Arguments.FirstOrDefault();
        if (firstArg?.Expression is LiteralExpressionSyntax lit && lit.Token.Value is string str)
            return str;
        if (firstArg?.Expression is InterpolatedStringExpressionSyntax interp)
            return interp.ToString();
        return string.Empty;
    }

    private static bool ContainsSqlKeyword(string text)
    {
        var upper = text.AsSpan();
        for (int i = 0; i < SqlKeywords.Length; i++)
        {
            if (upper.Contains(SqlKeywords[i].AsSpan(), StringComparison.OrdinalIgnoreCase))
                return true;
        }
        return false;
    }
}

/// <summary>
/// SQL call type for optimized routing
/// </summary>
internal enum SqlCallType : byte
{
    Unknown = 0,
    EfCore = 1,
    ExecuteSql = 2,
    Dapper = 3
}

/// <summary>
/// Minimal SQL call site - value type for zero allocation
/// </summary>
internal readonly struct SqlCallSite
{
    public readonly string MethodName;
    public readonly Location Location;
    public readonly string SqlText;
    public readonly string ContainingType;
    public readonly SqlCallType CallType;

    public SqlCallSite(string methodName, Location location, string sqlText, string containingType, SqlCallType callType)
    {
        MethodName = methodName;
        Location = location;
        SqlText = sqlText;
        ContainingType = containingType;
        CallType = callType;
    }

    public bool IsValid => Location != Location.None;
}

/// <summary>
/// Information about unvalidated SQL calls collected by the IDE light layer.
/// </summary>
internal sealed class UnvalidatedCallInfo
{
    public ImmutableArray<SqlCallSite> EfCoreCalls { get; init; } = [];
    public ImmutableArray<SqlCallSite> ExecuteSqlCalls { get; init; } = [];
    public ImmutableArray<SqlCallSite> DapperCalls { get; init; } = [];
    public ImmutableArray<SqlCallSite> RawSqlCalls { get; init; } = [];

    public bool HasAnyCalls => 
        EfCoreCalls.Length > 0 || 
        ExecuteSqlCalls.Length > 0 || 
        DapperCalls.Length > 0 || 
        RawSqlCalls.Length > 0;
}


/// <summary>
/// CI Heavy Layer: Full semantic analyzer with database connection.
/// This runs in CI pipeline and performs complete contract validation.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ContractValidationAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor[] AllDescriptors =
    [
        DiagnosticDescriptors.ParameterMismatch,
        DiagnosticDescriptors.DirectionMismatch,
        DiagnosticDescriptors.ColumnShapeMismatch,
        DiagnosticDescriptors.NullableMismatch,
        DiagnosticDescriptors.NamingConvention,
        DiagnosticDescriptors.LengthExceedsColumn,
        DiagnosticDescriptors.ByteLengthOverflow,
        DiagnosticDescriptors.InferredSizeFallback,
        DiagnosticDescriptors.OracleSyntaxInNonOracle,
        DiagnosticDescriptors.NonOracleFunctionInOracle,
        DiagnosticDescriptors.ProviderOptionMismatch,
        DiagnosticDescriptors.SqlServerSyntaxLeak,
        DiagnosticDescriptors.UnmappedTypeUsage,
        DiagnosticDescriptors.PhantomTable,
        DiagnosticDescriptors.PhantomColumn,
        DiagnosticDescriptors.MissingFromClause,
        DiagnosticDescriptors.SqlInjectionPattern
    ];

    /// <summary>Gets the diagnostics supported by this analyzer.</summary>
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => AllDescriptors.ToImmutableArray();

    /// <summary>Registers semantic analysis callbacks.</summary>
    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        
        // Register for semantic analysis of method invocations
        context.RegisterOperationAction(AnalyzeInvocation, OperationKind.Invocation);
    }

    private void AnalyzeInvocation(OperationAnalysisContext context)
    {
        var invocation = (IInvocationOperation)context.Operation;
        var method = invocation.TargetMethod;

        // Skip if marked with [SkipContractCheck] or an acknowledged marker comment
        if (HasSkipContractCheckAttribute(method) ||
            UnvalidatedSqlCallGenerator.HasDataGuardMarkerComment(invocation.Syntax))
            return;

        // Check for EF Core FromSqlRaw/FromSqlInterpolated
        if (IsEfCoreFromSqlMethod(method))
        {
            AnalyzeEfCoreFromSql(context, invocation, method);
            return;
        }

        // Check for ExecuteSqlRaw/ExecuteSqlInterpolated
        if (IsExecuteSqlMethod(method))
        {
            AnalyzeExecuteSql(context, invocation, method);
            return;
        }

        // Check for Dapper methods
        if (IsDapperQueryMethod(method))
        {
            AnalyzeDapperQuery(context, invocation, method);
            return;
        }
    }

    private static bool HasSkipContractCheckAttribute(IMethodSymbol method)
    {
        return method.GetAttributes().Any(attr =>
            attr.AttributeClass?.Name == "SkipContractCheckAttribute" ||
            attr.AttributeClass?.ToDisplayString() == "DataGuard.Contracts.SkipContractCheckAttribute");
    }

    private static bool IsEfCoreFromSqlMethod(IMethodSymbol method)
    {
        return (method.Name == "FromSqlRaw" || method.Name == "FromSqlInterpolated") &&
               method.ContainingType?.Name.StartsWith("DbSet", StringComparison.Ordinal) == true;
    }

    private static bool IsExecuteSqlMethod(IMethodSymbol method)
    {
        return method.Name is "ExecuteSqlRaw" or "ExecuteSqlRawAsync" 
            or "ExecuteSqlInterpolated" or "ExecuteSqlInterpolatedAsync";
    }

    private static bool IsDapperQueryMethod(IMethodSymbol method)
    {
        var name = method.Name;
        return name.StartsWith("Query", StringComparison.Ordinal) ||
               name.StartsWith("Execute", StringComparison.Ordinal);
    }

    private void AnalyzeEfCoreFromSql(OperationAnalysisContext context, IInvocationOperation invocation, IMethodSymbol method)
    {
        var sqlText = ExtractSqlFromArguments(invocation.Arguments);
        var entityType = GetEntityTypeFromDbSet(method);
        
        if (string.IsNullOrEmpty(sqlText) || entityType == null)
            return;

        // Real validation: extract SQL, run IDE-layer checks (no DB ground truth)
        var cancellationToken = context.CancellationToken;

        var sqlTextLower = sqlText.ToLowerInvariant();
        var isStoredProc = sqlTextLower.TrimStart().StartsWith("exec ") || sqlTextLower.TrimStart().StartsWith("execute ");

        // Validate using the inline checks (the heavy rules engine runs in the CLI)
        var violations = ValidateEntityContract(sqlText, isStoredProc, context.CancellationToken);
        
        foreach (var violation in violations)
        {
            var diagnostic = Diagnostic.Create(
                GetDiagnosticDescriptor(violation.RuleId),
                violation.Location ?? invocation.Syntax.GetLocation(),
                violation.Message);
            context.ReportDiagnostic(diagnostic);
        }
    }

    private void AnalyzeExecuteSql(OperationAnalysisContext context, IInvocationOperation invocation, IMethodSymbol method)
    {
        var sqlText = ExtractSqlFromArguments(invocation.Arguments);
        if (string.IsNullOrEmpty(sqlText))
            return;

        var cancellationToken = context.CancellationToken;
        var sqlTextLower = sqlText.ToLowerInvariant();
        var isStoredProc = sqlTextLower.TrimStart().StartsWith("exec ") || sqlTextLower.TrimStart().StartsWith("execute ");

        // For ExecuteSqlRaw, we validate the SQL against known contracts
        var violations = ValidateRawSqlContract(sqlText, isStoredProc, context.CancellationToken);
        
        foreach (var violation in violations)
        {
            var diagnostic = Diagnostic.Create(
                GetDiagnosticDescriptor(violation.RuleId),
                violation.Location ?? invocation.Syntax.GetLocation(),
                violation.Message);
            context.ReportDiagnostic(diagnostic);
        }
    }

    private void AnalyzeDapperQuery(OperationAnalysisContext context, IInvocationOperation invocation, IMethodSymbol method)
    {
        var sqlText = ExtractSqlFromArguments(invocation.Arguments);
        if (string.IsNullOrEmpty(sqlText))
            return;

        var cancellationToken = context.CancellationToken;
        var sqlTextLower = sqlText.ToLowerInvariant();
        var isStoredProc = sqlTextLower.TrimStart().StartsWith("exec ") || sqlTextLower.TrimStart().StartsWith("execute ");

        // For Dapper queries, validate the SQL against known contracts
        var violations = ValidateRawSqlContract(sqlText, isStoredProc, cancellationToken);
        
        foreach (var violation in violations)
        {
            var diagnostic = Diagnostic.Create(
                GetDiagnosticDescriptor(violation.RuleId),
                violation.Location ?? invocation.Syntax.GetLocation(),
                violation.Message);
            context.ReportDiagnostic(diagnostic);
        }
    }

    private List<AnalyzerViolation> ValidateEntityContract(string sqlText, bool isStoredProc, CancellationToken cancellationToken)
    {
        var violations = new List<AnalyzerViolation>();

        // The heavy rules engine (parameter count/type/direction, column shape,
        // nullability, phantom identifiers) runs in the CLI against database ground
        // truth. The IDE layer only performs syntax-level checks that need no DB.
        if (!isStoredProc && ContainsSqlInjectionPatterns(sqlText))
        {
            violations.Add(new AnalyzerViolation(
                "DG099",
                "Potential SQL injection pattern detected",
                DiagnosticSeverity.Warning,
                Location.None));
        }

        return violations;
    }

    private List<AnalyzerViolation> ValidateRawSqlContract(string sqlText, bool isStoredProc, CancellationToken cancellationToken)
    {
        var violations = new List<AnalyzerViolation>();
        
        // Check for potential SQL injection patterns
        if (ContainsSqlInjectionPatterns(sqlText))
        {
            violations.Add(new AnalyzerViolation(
                "DG099",
                "Potential SQL injection pattern detected",
                DiagnosticSeverity.Warning,
                Location.None));
        }
        
        // Additional validation for stored procedure calls
        if (isStoredProc)
        {
            // Verify the SQL has a valid EXEC or EXECUTE prefix
            var sqlLower = sqlText.ToLowerInvariant();
            if (!sqlLower.StartsWith("exec ") && !sqlLower.StartsWith("execute "))
            {
                violations.Add(new AnalyzerViolation(
                    "DG002",
                    "Stored procedure call must start with EXEC or EXECUTE",
                    DiagnosticSeverity.Warning,
                    Location.None));
            }
            // Minimum SQL structure is already validated above.
        }
        
        // Check for common raw SQL patterns
        if (sqlText.IndexOf("SELECT", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            // For SELECT queries, verify they reference valid entities
            var hasFromClause = sqlText.IndexOf("FROM", StringComparison.OrdinalIgnoreCase) >= 0;
            if (!hasFromClause)
            {
                violations.Add(new AnalyzerViolation(
                    "DG098",
                    "Raw SQL query missing FROM clause",
                    DiagnosticSeverity.Warning,
                    Location.None));
            }
        }
        
        return violations;
    }

    private bool ContainsSqlInjectionPatterns(string sqlText)
    {
        var sqlLower = sqlText.ToLowerInvariant();
        var injectionPatterns = new[]
        {
            ";--", "';--", "';--", "1=1", "1=1--", "' or '1'='1",
            "union select", "drop table", "drop database", "truncate table",
            "xp_cmdshell", "sp_executesql", "execute immediate"
        };
        
        return injectionPatterns.Any(p => sqlLower.Contains(p));
    }

    private bool IsStoredProcedureCall(string sqlText)
    {
        var sqlLower = sqlText.TrimStart().ToLowerInvariant();
        return sqlLower.StartsWith("exec ") || sqlLower.StartsWith("execute ");
    }



    private static string ExtractSqlFromArguments(ImmutableArray<IArgumentOperation> arguments)
    {
        if (arguments.IsDefaultOrEmpty)
            return string.Empty;

        var firstArgSyntax = arguments[0].Syntax;
        if (firstArgSyntax is LiteralExpressionSyntax literal && literal.Token.Value is string str)
            return str;

        if (firstArgSyntax is InterpolatedStringExpressionSyntax interp)
            return interp.ToString();

        return string.Empty;
    }

    private static ITypeSymbol? GetEntityTypeFromDbSet(IMethodSymbol method)
    {
        if (method.ContainingType is INamedTypeSymbol dbSet &&
            dbSet.Name.StartsWith("DbSet", StringComparison.Ordinal) &&
            dbSet.TypeArguments.Length == 1)
        {
            return dbSet.TypeArguments[0];
        }
        return null;
    }


    private DiagnosticDescriptor GetDiagnosticDescriptor(string ruleId)
    {
        return AllDescriptors.FirstOrDefault(d => d.Id == ruleId) 
            ?? DiagnosticDescriptors.ParameterMismatch;
    }


}

/// <summary>
/// IDE-layer violation produced by syntax-level checks. The heavy rules engine
/// lives in DataGuard.Core and runs in the CLI (net9.0); this netstandard2.0
/// analyzer only reports checks that need no database ground truth.
/// </summary>
internal sealed class AnalyzerViolation
{
    public AnalyzerViolation(string ruleId, string message, DiagnosticSeverity severity, Location? location)
    {
        RuleId = ruleId;
        Message = message;
        Severity = severity;
        Location = location;
    }

    public string RuleId { get; }
    public string Message { get; }
    public DiagnosticSeverity Severity { get; }
    public Location? Location { get; }
}