// <auto-generated/>
// This file contains both IDE (light) and CI (heavy) analyzers.
// The IDE layer uses IIncrementalGenerator for syntax-only, fast analysis.
// The CI layer uses full semantic analysis with database connection.

using System;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.IncrementalGenerators;
using Microsoft.CodeAnalysis.Operations;
using DataGuard.Core.Abstractions;

namespace DataGuard.Analyzers;

/// <summary>
/// Diagnostic IDs for DataGuard contract validation.
/// </summary>
public static class DiagnosticIds
{
    public const string UnvalidatedSqlCall = "DG001";       // IDE light: marks unvalidated SQL calls
    public const string ParameterMismatch = "DG002";         // CI heavy: parameter count/type mismatch
    public const string DirectionMismatch = "DG003";         // CI heavy: IN/OUT/INOUT direction mismatch
    public const string ColumnShapeMismatch = "DG004";       // CI heavy: result set column mismatch
    public const string NullableMismatch = "DG005";          // CI heavy: nullable mismatch
    public const string NamingConvention = "DG006";          // CI heavy: naming convention violation
    public const string LengthExceedsColumn = "DG007";       // CI heavy: entity length > column length
    public const string ByteLengthOverflow = "DG008";        // CI heavy: byte semantics overflow risk
    public const string InferredSizeFallback = "DG009";      // CI heavy: NVARCHAR2(2000) fallback risk
    public const string OracleSyntaxInNonOracle = "DG010";   // CI heavy: Oracle syntax in non-Oracle context
    public const string NonOracleFunctionInOracle = "DG011"; // CI heavy: SQL Server syntax in Oracle
    public const string ProviderOptionMismatch = "DG012";    // CI heavy: missing UseOracle
    public const string SqlServerSyntaxLeak = "DG013";       // CI heavy: EXEC dbo. in Oracle
    public const string UnmappedTypeUsage = "DG014";         // CI heavy: unmapped type in Oracle
}

/// <summary>
/// Shared diagnostic descriptors for both IDE and CI layers.
/// </summary>
internal static class DiagnosticDescriptors
{
    // IDE Light Layer - Syntax only, very fast
    public static readonly DiagnosticDescriptor UnvalidatedSqlCall = new(
        id: DiagnosticIds.UnvalidatedSqlCall,
        title: "SQL call not validated",
        messageFormat: "SQL call '{0}' not validated - run 'dataguard check' for full validation",
        category: "DataGuard.IDE",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Marks SQL calls that haven't been validated against database schema. Run full validation in CI.");

    // CI Heavy Layer - Full semantic validation
    public static readonly DiagnosticDescriptor ParameterMismatch = new(
        id: DiagnosticIds.ParameterMismatch,
        title: "Parameter count/type mismatch",
        messageFormat: "Parameter mismatch: {0}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Stored procedure parameter count or type doesn't match call site.");

    public static readonly DiagnosticDescriptor DirectionMismatch = new(
        id: DiagnosticIds.DirectionMismatch,
        title: "Parameter direction mismatch",
        messageFormat: "Parameter '{0}' direction mismatch: expected {1}, got {2}",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Parameter IN/OUT/INOUT direction doesn't match C# out/ref modifiers.");

    public static readonly DiagnosticDescriptor ColumnShapeMismatch = new(
        id: DiagnosticIds.ColumnShapeMismatch,
        title: "Result set column shape mismatch",
        messageFormat: "Result set missing required column '{0}' for entity '{1}'",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Stored procedure result set doesn't match entity properties.");

    public static readonly DiagnosticDescriptor NullableMismatch = new(
        id: DiagnosticIds.NullableMismatch,
        title: "Nullable mismatch",
        messageFormat: "Column '{0}' is NOT NULL but entity property '{1}' is nullable",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Database column nullability doesn't match entity property.");

    public static readonly DiagnosticDescriptor NamingConvention = new(
        id: DiagnosticIds.NamingConvention,
        title: "Naming convention violation",
        messageFormat: "Column '{0}' doesn't match entity property '{1}' per naming convention",
        category: "DataGuard.Contracts",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Column/property naming convention mismatch (snake_case vs PascalCase).");

    public static readonly DiagnosticDescriptor LengthExceedsColumn = new(
        id: DiagnosticIds.LengthExceedsColumn,
        title: "Entity length exceeds column length",
        messageFormat: "Entity property '{0}' MaxLength={1} exceeds column '{2}' length={3}",
        category: "DataGuard.Length",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Entity property max length exceeds database column length - truncation risk.");

    public static readonly DiagnosticDescriptor ByteLengthOverflow = new(
        id: DiagnosticIds.ByteLengthOverflow,
        title: "Byte length overflow risk",
        messageFormat: "Byte overflow risk: property '{0}' may exceed column '{1}' byte capacity in {2} semantics",
        category: "DataGuard.Length",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Unicode data may exceed column byte capacity in BYTE length semantics.");

    public static readonly DiagnosticDescriptor InferredSizeFallback = new(
        id: DiagnosticIds.InferredSizeFallback,
        title: "Inferred size fallback risk",
        messageFormat: "EF Core will infer NVARCHAR2(2000) for '{0}' - may cause ORA-12899 if values exceed 2000 chars",
        category: "DataGuard.Length",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "EF Core Oracle provider falls back to NVARCHAR2(2000) when size is null and Unicode=true.");

    public static readonly DiagnosticDescriptor OracleSyntaxInNonOracle = new(
        id: DiagnosticIds.OracleSyntaxInNonOracle,
        title: "Oracle syntax in non-Oracle context",
        messageFormat: "Oracle-specific syntax '{0}' used but provider is not Oracle",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Oracle-specific syntax (DECODE, NVL, (+), DUAL, etc.) used in non-Oracle context.");

    public static readonly DiagnosticDescriptor NonOracleFunctionInOracle = new(
        id: DiagnosticIds.NonOracleFunctionInOracle,
        title: "Non-Oracle function in Oracle context",
        messageFormat: "Non-Oracle function '{0}' used in Oracle context",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "SQL Server functions (ISNULL, TOP, GETDATE) used in Oracle context.");

    public static readonly DiagnosticDescriptor ProviderOptionMismatch = new(
        id: DiagnosticIds.ProviderOptionMismatch,
        title: "Provider option mismatch",
        messageFormat: "Oracle metadata reader used but DbContext doesn't have UseOracle registered",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Oracle metadata reader requires UseOracle in DbContextOptions.");

    public static readonly DiagnosticDescriptor SqlServerSyntaxLeak = new(
        id: DiagnosticIds.SqlServerSyntaxLeak,
        title: "SQL Server syntax in Oracle",
        messageFormat: "SQL Server EXEC syntax used in Oracle context - use BEGIN/END block",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "SQL Server EXEC dbo.Proc syntax leaked into Oracle code.");

    public static readonly DiagnosticDescriptor UnmappedTypeUsage = new(
        id: DiagnosticIds.UnmappedTypeUsage,
        title: "Unmapped type usage",
        messageFormat: "Type '{0}' used with Oracle EF Core raw SQL but not mapped by provider",
        category: "DataGuard.Dialect",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Oracle EF Core 8+ raw SQL requires mapped types.");
}

/// <summary>
/// IDE Light Layer: Incremental generator that marks unvalidated SQL calls with syntax-only analysis.
/// This runs on every keystroke and must be extremely fast (~ms).
/// Optimized for zero-allocation, minimal GC pressure, and incremental caching.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class UnvalidatedSqlCallGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Descriptor = DiagnosticDescriptors.UnvalidatedSqlCall;

    // Pre-computed method name sets for fast lookup (no allocation)
    private static readonly HashSet<string> EfCoreMethods = new(StringComparer.Ordinal)
    {
        "FromSqlRaw", "FromSqlInterpolated"
    };

    private static readonly HashSet<string> ExecuteSqlMethods = new(StringComparer.Ordinal)
    {
        "ExecuteSqlRaw", "ExecuteSqlRawAsync", 
        "ExecuteSqlInterpolated", "ExecuteSqlInterpolatedAsync"
    };

    // SQL keywords for fast literal detection
    private static readonly string[] SqlKeywords = 
    {
        "SELECT", "INSERT", "UPDATE", "DELETE", "EXEC", "BEGIN", "WITH", "MERGE"
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Single provider that identifies all SQL call sites in one pass
        // Uses syntax-only predicates for maximum speed
        var sqlCalls = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPotentialSqlCall(node),
                transform: static (ctx, _) => ExtractSqlCallSite(ctx))
            .Where(static site => site != null)!;

        // Direct emission - no intermediate aggregation, no allocations
        context.RegisterSourceOutput(sqlCalls, static (ctx, site) => 
        {
            if (site != null)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    Descriptor,
                    site.Location,
                    site.MethodName));
            }
        });
    }

    /// <summary>
    /// Ultra-fast syntax-only predicate - no allocations, no string operations
    /// </summary>
    private static bool IsPotentialSqlCall(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax invocation)
            return false;

        // Fast path: check method name first (most common filter)
        if (invocation.Expression is not MemberAccessExpressionSyntax memberAccess)
            return false;

        var methodName = memberAccess.Name.Identifier.ValueText;

        // Check against pre-computed sets - O(1) lookup
        if (EfCoreMethods.Contains(methodName) || ExecuteSqlMethods.Contains(methodName))
            return true;

        // Dapper methods - check prefix (slightly slower but rare)
        if (methodName.StartsWith("Query", StringComparison.Ordinal) ||
            methodName.StartsWith("Execute", StringComparison.Ordinal))
            return true;

        // Raw SQL detection - only if first arg is string literal
        var firstArg = invocation.ArgumentList.Arguments.FirstOrDefault();
        return firstArg?.Expression is LiteralExpressionSyntax lit && 
               lit.Token.Value is string str && 
               ContainsSqlKeyword(str);
    }

    private static bool ContainsSqlKeyword(ReadOnlySpan<char> text)
    {
        // Fast path: check common SQL keywords without allocation
        for (int i = 0; i < SqlKeywords.Length; i++)
        {
            if (text.Contains(SqlKeywords[i].AsSpan(), StringComparison.OrdinalIgnoreCase))
                return true;
        }
        return false;
    }

    /// <summary>
    /// Extracts minimal call site info - zero allocation when possible
    /// </summary>
    private static SqlCallSite? ExtractSqlCallSite(GeneratorSyntaxContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var memberAccess = (MemberAccessExpressionSyntax)invocation.Expression;
        var methodName = memberAccess.Name.Identifier.ValueText;

        // Determine call type from method name (fast path)
        var callType = GetCallType(methodName);

        // Skip if not a recognized SQL method
        if (callType == SqlCallType.Unknown)
            return null;

        // Extract SQL text only for literal/interpolated strings (cheap)
        var sqlText = ExtractSqlTextFast(invocation);
        if (string.IsNullOrEmpty(sqlText) && callType != SqlCallType.Dapper)
            return null; // No SQL text, likely not a real SQL call

        // Get containing type name only for EF Core (needed for diagnostics)
        string containingType = "";
        if (callType == SqlCallType.EfCore)
        {
            var symbolInfo = context.SemanticModel.GetSymbolInfo(memberAccess.Expression, context.CancellationToken);
            if (symbolInfo.Symbol is IMethodSymbol method && 
                method.ContainingType?.Name.StartsWith("DbSet", StringComparison.Ordinal) == true)
            {
                containingType = method.ContainingType.ToDisplayString();
            }
            else
            {
                return null; // Not on DbSet<T>
            }
        }

        return new SqlCallSite(methodName, invocation.GetLocation(), sqlText, containingType, callType);
    }

    private static SqlCallType GetCallType(string methodName)
    {
        if (EfCoreMethods.Contains(methodName)) return SqlCallType.EfCore;
        if (ExecuteSqlMethods.Contains(methodName)) return SqlCallType.ExecuteSql;
        if (methodName.StartsWith("Query", StringComparison.Ordinal) || 
            methodName.StartsWith("Execute", StringComparison.Ordinal)) 
            return SqlCallType.Dapper;
        return SqlCallType.Unknown;
    }

    private static string ExtractSqlTextFast(InvocationExpressionSyntax invocation)
    {
        var firstArg = invocation.ArgumentList.Arguments.FirstOrDefault();
        if (firstArg?.Expression is LiteralExpressionSyntax lit && lit.Token.Value is string str)
            return str;
        if (firstArg?.Expression is InterpolatedStringExpressionSyntax interp)
            return interp.ToString();
        return string.Empty;
    }

    private static bool ContainsSqlKeyword(string text)
    {
        var upper = text.AsSpan();
        for (int i = 0; i < SqlKeywords.Length; i++)
        {
            if (upper.Contains(SqlKeywords[i].AsSpan(), StringComparison.OrdinalIgnoreCase))
                return true;
        }
        return false;
    }
}

/// <summary>
/// SQL call type for optimized routing
/// </summary>
internal enum SqlCallType : byte
{
    Unknown = 0,
    EfCore = 1,
    ExecuteSql = 2,
    Dapper = 3
}

/// <summary>
/// Minimal SQL call site - value type for zero allocation
/// </summary>
internal readonly struct SqlCallSite
{
    public readonly string MethodName;
    public readonly Location Location;
    public readonly string SqlText;
    public readonly string ContainingType;
    public readonly SqlCallType CallType;

    public SqlCallSite(string methodName, Location location, string sqlText, string containingType, SqlCallType callType)
    {
        MethodName = methodName;
        Location = location;
        SqlText = sqlText;
        ContainingType = containingType;
        CallType = callType;
    }

    public bool IsValid => Location != Location.None;
}

/// <summary>
/// Information about unvalidated SQL calls collected by the IDE light layer.
/// </summary>
internal sealed class UnvalidatedCallInfo
{
    public ImmutableArray<SqlCallSite> EfCoreCalls { get; init; } = [];
    public ImmutableArray<SqlCallSite> ExecuteSqlCalls { get; init; } = [];
    public ImmutableArray<SqlCallSite> DapperCalls { get; init; } = [];
    public ImmutableArray<SqlCallSite> RawSqlCalls { get; init; } = [];

    public bool HasAnyCalls => 
        EfCoreCalls.Length > 0 || 
        ExecuteSqlCalls.Length > 0 || 
        DapperCalls.Length > 0 || 
        RawSqlCalls.Length > 0;
}

/// <summary>
/// A SQL call site that needs validation.
/// </summary>
internal sealed record SqlCallSite(
    string MethodName,
    Location Location,
    string SqlText,
    string ContainingType);

/// <summary>
/// CI Heavy Layer: Full semantic analyzer with database connection.
/// This runs in CI pipeline and performs complete contract validation.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ContractValidationAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor[] AllDescriptors =
    [
        DiagnosticDescriptors.ParameterMismatch,
        DiagnosticDescriptors.DirectionMismatch,
        DiagnosticDescriptors.ColumnShapeMismatch,
        DiagnosticDescriptors.NullableMismatch,
        DiagnosticDescriptors.NamingConvention,
        DiagnosticDescriptors.LengthExceedsColumn,
        DiagnosticDescriptors.ByteLengthOverflow,
        DiagnosticDescriptors.InferredSizeFallback,
        DiagnosticDescriptors.OracleSyntaxInNonOracle,
        DiagnosticDescriptors.NonOracleFunctionInOracle,
        DiagnosticDescriptors.ProviderOptionMismatch,
        DiagnosticDescriptors.SqlServerSyntaxLeak,
        DiagnosticDescriptors.UnmappedTypeUsage
    ];

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => AllDescriptors.ToImmutableArray();

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        
        // Register for semantic analysis of method invocations
        context.RegisterOperationAction(AnalyzeInvocation, OperationKind.Invocation);
    }

    private void AnalyzeInvocation(OperationAnalysisContext context)
    {
        var invocation = (IInvocationOperation)context.Operation;
        var method = invocation.TargetMethod;
        
        // Skip if marked with [SkipContractCheck]
        if (HasSkipContractCheckAttribute(method))
            return;

        // Check for EF Core FromSqlRaw/FromSqlInterpolated
        if (IsEfCoreFromSqlMethod(method))
        {
            AnalyzeEfCoreFromSql(context, invocation, method);
            return;
        }

        // Check for ExecuteSqlRaw/ExecuteSqlInterpolated
        if (IsExecuteSqlMethod(method))
        {
            AnalyzeExecuteSql(context, invocation, method);
            return;
        }

        // Check for Dapper methods
        if (IsDapperQueryMethod(method))
        {
            AnalyzeDapperQuery(context, invocation, method);
            return;
        }
    }

    private static bool HasSkipContractCheckAttribute(IMethodSymbol method)
    {
        return method.GetAttributes().Any(attr => 
            attr.AttributeClass?.Name == "SkipContractCheckAttribute" ||
            attr.AttributeClass?.ToDisplayString() == "DataGuard.Attributes.SkipContractCheckAttribute");
    }

    private static bool IsEfCoreFromSqlMethod(IMethodSymbol method)
    {
        return (method.Name == "FromSqlRaw" || method.Name == "FromSqlInterpolated") &&
               method.ContainingType?.Name.StartsWith("DbSet", StringComparison.Ordinal) == true;
    }

    private static bool IsExecuteSqlMethod(IMethodSymbol method)
    {
        return method.Name is "ExecuteSqlRaw" or "ExecuteSqlRawAsync" 
            or "ExecuteSqlInterpolated" or "ExecuteSqlInterpolatedAsync";
    }

    private static bool IsDapperQueryMethod(IMethodSymbol method)
    {
        var name = method.Name;
        return name.StartsWith("Query", StringComparison.Ordinal) ||
               name.StartsWith("Execute", StringComparison.Ordinal);
    }

    private void AnalyzeEfCoreFromSql(OperationAnalysisContext context, IInvocationOperation invocation, IMethodSymbol method)
    {
        // Extract SQL text and entity type
        var sqlText = ExtractSqlFromArguments(invocation.Arguments);
        var entityType = GetEntityTypeFromDbSet(method);
        
        if (string.IsNullOrEmpty(sqlText) || entityType == null)
            return;

        // In CI heavy layer, this would connect to DB and validate
        // For now, emit diagnostic that full validation should run in CI
        var diagnostic = Diagnostic.Create(
            DiagnosticDescriptors.ParameterMismatch,
            invocation.Syntax.GetLocation(),
            $"EF Core {method.Name} call requires full contract validation in CI");
        
        context.ReportDiagnostic(diagnostic);
    }

    private void AnalyzeExecuteSql(OperationAnalysisContext context, IInvocationOperation invocation, IMethodSymbol method)
    {
        var sqlText = ExtractSqlFromArguments(invocation.Arguments);
        if (string.IsNullOrEmpty(sqlText))
            return;

        var diagnostic = Diagnostic.Create(
            DiagnosticDescriptors.ParameterMismatch,
            invocation.Syntax.GetLocation(),
            $"ExecuteSqlRaw call requires full contract validation in CI");
        
        context.ReportDiagnostic(diagnostic);
    }

    private void AnalyzeDapperQuery(OperationAnalysisContext context, IInvocationOperation invocation, IMethodSymbol method)
    {
        var sqlText = ExtractSqlFromArguments(invocation.Arguments);
        if (string.IsNullOrEmpty(sqlText))
            return;

        var diagnostic = Diagnostic.Create(
            DiagnosticDescriptors.ParameterMismatch,
            invocation.Syntax.GetLocation(),
            $"Dapper {method.Name} call requires full contract validation in CI");
        
        context.ReportDiagnostic(diagnostic);
    }

    private static string? ExtractSqlFromArguments(ImmutableArray<IOperation> arguments)
    {
        if (arguments.Length == 0) return null;
        
        var firstArg = arguments[0];
        if (firstArg is ILiteralOperation lit && lit.Value is string str)
            return str;
        
        // For interpolated strings, we'd need more complex extraction
        return firstArg.Syntax?.ToString();
    }

    private static ITypeSymbol? GetEntityTypeFromDbSet(IMethodSymbol method)
    {
        // DbSet<T> -> get T
        return method.ContainingType?.TypeArguments.FirstOrDefault();
    }
}

/// <summary>
/// Attribute to skip contract validation for dynamic SQL or complex cases.
/// </summary>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
public sealed class SkipContractCheckAttribute : Attribute
{
    public string? Reason { get; set; }
}

/// <summary>
/// Attribute to declare expected column for manual mode ground truth.
/// </summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = true)]
public sealed class ExpectedColumnAttribute : Attribute
{
    public ExpectedColumnAttribute(string columnName, string clrTypeName)
    {
        ColumnName = columnName;
        ClrTypeName = clrTypeName;
    }

    public string ColumnName { get; }
    public string ClrTypeName { get; }
    public bool IsNullable { get; set; }
    public int? MaxLength { get; set; }
}

/// <summary>
/// Attribute to declare expected stored procedure parameter.
/// </summary>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public sealed class ExpectedSpParameterAttribute : Attribute
{
    public ExpectedSpParameterAttribute(string name, string dbType, string direction)
    {
        Name = name;
        DbType = dbType;
        Direction = Enum.Parse<ParameterDirection>(direction);
    }

    public string Name { get; }
    public string DbType { get; }
    public ParameterDirection Direction { get; set; }
    public int? MaxLength { get; set; }
    public byte? Precision { get; set; }
    public byte? Scale { get; set; }
}