#!/usr/bin/env python3
"""Render the README rule tables from the rule sources (stdlib only, no dotnet call).

Sources, all parsed as text:
  * ``src/DataGuard.Cli/ProviderRuleCatalog.cs`` ``RuleTitles`` -- the CLI display title of every engine rule;
  * every ``RuleId => "..."`` rule class under ``src/`` with its ``Name =>`` and ``Description =>``
    (grouped by assembly: Core, Oracle, MySQL, PostgreSQL);
  * ``src/DataGuard.Analyzers`` ``DiagnosticIds`` constants and ``DiagnosticDescriptor`` titles/descriptions
    (analyzer-only IDs: DG001 plus every analyzer ID that is not an engine rule, such as DG097/DG098/DG099);
  * ``RuleId = "DG1xxx"`` assessment findings under ``src/DataGuard.Core/Assessment`` with their message template.

The table is written between ``<!-- rule-table:start -->`` and ``<!-- rule-table:end -->`` in README.md (English
headings) and README.vi.md (Vietnamese headings; rule titles stay the canonical English names).

Usage:
  python3 scripts/gen_rule_table.py            # rewrite both READMEs in place
  python3 scripts/gen_rule_table.py --check    # exit 1 when a README block differs from the generated one
  python3 scripts/gen_rule_table.py --print en # print the generated block
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

START_MARKER = "<!-- rule-table:start -->"
END_MARKER = "<!-- rule-table:end -->"

CATALOG_PATH = Path("src/DataGuard.Cli/ProviderRuleCatalog.cs")
ANALYZERS_DIR = Path("src/DataGuard.Analyzers")
ASSESSMENT_DIR = Path("src/DataGuard.Core/Assessment")
READMES = {"en": Path("README.md"), "vi": Path("README.vi.md")}

GROUP_ORDER = ("core", "oracle", "mysql", "postgresql", "analyzer", "assessment")

GROUP_BY_PROJECT = {
    "DataGuard.Core": "core",
    "DataGuard.Oracle.Adapter": "oracle",
    "DataGuard.MySql.Adapter": "mysql",
    "DataGuard.PostgreSql.Adapter": "postgresql",
}

# Rule classes that are samples or test doubles, not product rules.
EXCLUDED_RULE_IDS = re.compile(r"^(CUSTOM|TEST|DUMMY)", re.IGNORECASE)

ASSESSMENT_PACKS = {
    "InventoryPack": "Inventory",
    "DependencyHealthPack": "Dependency health",
    "BuildCiPack": "Build/CI",
    "SecretsPack": "Configuration and secrets",
    "AssessmentEngine": "Remote advisory (OSV, opt-in)",
}

LABELS = {
    "en": {
        "heading": {
            "core": "Core engine (every provider)",
            "oracle": "Oracle adapter",
            "mysql": "MySQL adapter",
            "postgresql": "PostgreSQL adapter",
            "analyzer": "Analyzer-only (Roslyn, IDE/build)",
            "assessment": "Assessment (`dataguard assess`)",
        },
        "columns": ("ID", "Rule", "Description"),
        "note": "Generated by `scripts/gen_rule_table.py` from `ProviderRuleCatalog.RuleTitles` and the rule sources; "
        "do not edit by hand (`--check` runs in `scripts/verify_docs_sync.sh`).",
    },
    "vi": {
        "heading": {
            "core": "Engine lõi (mọi provider)",
            "oracle": "Adapter Oracle",
            "mysql": "Adapter MySQL",
            "postgresql": "Adapter PostgreSQL",
            "analyzer": "Chỉ analyzer (Roslyn, IDE/build)",
            "assessment": "Assessment (`dataguard assess`)",
        },
        "columns": ("ID", "Quy tắc", "Mô tả"),
        "note": "Sinh bởi `scripts/gen_rule_table.py` từ `ProviderRuleCatalog.RuleTitles` và source của rule; "
        "không sửa tay (`--check` chạy trong `scripts/verify_docs_sync.sh`). Tên/mô tả rule giữ nguyên tiếng Anh theo source.",
    },
}

_STRING = r'"((?:[^"\\]|\\.)*)"'
_CATALOG_ENTRY = re.compile(r'\[\s*"(?P<id>[A-Z]+\d+)"\s*\]\s*=\s*' + _STRING)
# A class declaration at the start of a line, so "class" inside a string or comment does not split a class body.
_CLASS = re.compile(
    r"^[ \t]*(?:(?:public|internal|private|protected|sealed|static|abstract|partial|file|unsafe|new)\s+)*class\s+(?P<name>\w+)",
    re.MULTILINE,
)
_RULE_ID = re.compile(r"\bRuleId\s*=>\s*(?:" + _STRING + r"|(?P<constant>\w+)\s*;)")
_RULE_ID_CONST = re.compile(r"\bconst\s+string\s+(?P<field>\w*RuleId)\s*=\s*" + _STRING)
_NAME = re.compile(r"\bName\s*=>\s*" + _STRING)
_DESCRIPTION = re.compile(r"\bDescription\s*=>\s*" + _STRING)
_DIAGNOSTIC_ID_CONST = re.compile(r"\bconst\s+string\s+(?P<field>\w+)\s*=\s*" + _STRING)
_DESCRIPTOR = re.compile(
    r"\bid\s*:\s*(?:DiagnosticIds\.(?P<field>\w+)|" + _STRING + r")\s*,\s*title\s*:\s*" + r'"(?P<title>(?:[^"\\]|\\.)*)"'
    r"(?P<rest>.*?)\);",
    re.DOTALL,
)
_DESCRIPTOR_DESCRIPTION = re.compile(r"\bdescription\s*:\s*" + _STRING)
_ASSESSMENT_RULE = re.compile(r'\bRuleId\s*=\s*"(?P<id>DG1\d{3})"')
_MESSAGE_START = re.compile(r'\bMessage\s*=\s*(?P<interpolated>\$?)"')


@dataclass(frozen=True)
class Rule:
    rule_id: str
    title: str
    description: str
    group: str


class RuleSourceError(Exception):
    """Raised when the sources are inconsistent (for example a catalog ID without any implementation)."""


def _unescape(text: str) -> str:
    return text.replace('\\"', '"').replace("\\\\", "\\")


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _id_key(rule_id: str) -> tuple[str, int]:
    match = re.match(r"([A-Z]+)(\d+)$", rule_id)
    return (match.group(1), int(match.group(2))) if match else (rule_id, 0)


def _source_files(root: Path, directory: Path) -> list[Path]:
    base = root / directory
    if not base.is_dir():
        return []
    return sorted(
        path
        for path in base.rglob("*.cs")
        if not ({"bin", "obj"} & set(path.relative_to(root).parts))
    )


def read_catalog_titles(root: Path) -> dict[str, str]:
    """Returns ``ProviderRuleCatalog.RuleTitles`` (ID -> title)."""
    text = (root / CATALOG_PATH).read_text(encoding="utf-8")
    start = text.find("RuleTitles")
    if start < 0:
        raise RuleSourceError(f"{CATALOG_PATH}: RuleTitles not found")
    end = text.find("};", start)
    block = text[start:end]
    titles = {match.group("id"): _unescape(match.group(2)) for match in _CATALOG_ENTRY.finditer(block)}
    if not titles:
        raise RuleSourceError(f"{CATALOG_PATH}: RuleTitles has no entries")
    return titles


def read_rule_classes(root: Path) -> dict[str, tuple[str, str, str]]:
    """Returns rule ID -> (group, Name, Description) for every ``RuleId => "..."`` class in a product project."""
    rules: dict[str, tuple[str, str, str]] = {}
    for path in _source_files(root, Path("src")):
        project = path.relative_to(root).parts[1]
        group = GROUP_BY_PROJECT.get(project)
        if group is None:
            continue
        text = path.read_text(encoding="utf-8")
        classes = list(_CLASS.finditer(text))
        for index, class_match in enumerate(classes):
            body = text[class_match.end(): classes[index + 1].start() if index + 1 < len(classes) else len(text)]
            rule_id_match = _RULE_ID.search(body)
            if rule_id_match is None:
                continue
            # RuleId => "DG015" or RuleId => MismatchRuleId with const string MismatchRuleId = "DG018".
            constants = {const.group("field"): const.group(2) for const in _RULE_ID_CONST.finditer(body)}
            rule_id = rule_id_match.group(1) or constants.get(rule_id_match.group("constant") or "", "")
            if not rule_id or EXCLUDED_RULE_IDS.match(rule_id):
                continue
            name = _NAME.search(body)
            description = _DESCRIPTION.search(body)
            rules.setdefault(
                rule_id,
                (
                    group,
                    _unescape(name.group(1)) if name else "",
                    _unescape(description.group(1)) if description else "",
                ),
            )
            # Secondary IDs the same rule reports (for example DG020 "undetermined shape" next to DG018).
            for field, secondary in constants.items():
                if secondary != rule_id and not EXCLUDED_RULE_IDS.match(secondary):
                    rules.setdefault(secondary, (group, "", f"Reported by `{class_match.group('name')}` (`{field}`)"))
    return rules


def read_analyzer_descriptors(root: Path) -> dict[str, tuple[str, str]]:
    """Returns analyzer diagnostic ID -> (title, description) from ``DiagnosticIds`` and ``DiagnosticDescriptor``s."""
    files = _source_files(root, ANALYZERS_DIR)
    texts = [path.read_text(encoding="utf-8") for path in files]
    constants: dict[str, str] = {}
    for text in texts:
        for match in _DIAGNOSTIC_ID_CONST.finditer(text):
            value = match.group(2)
            if re.fullmatch(r"DG\d{3}", value):
                constants[match.group("field")] = value
    descriptors: dict[str, tuple[str, str]] = {}
    for text in texts:
        for match in _DESCRIPTOR.finditer(text):
            rule_id = constants.get(match.group("field") or "", match.group(2) or "")
            if not rule_id:
                continue
            description = _DESCRIPTOR_DESCRIPTION.search(match.group("rest"))
            descriptors.setdefault(
                rule_id,
                (_unescape(match.group("title")), _unescape(description.group(1)) if description else ""),
            )
    for rule_id in constants.values():
        descriptors.setdefault(rule_id, ("", ""))
    return descriptors


def read_assessment_rules(root: Path) -> dict[str, tuple[str, str]]:
    """Returns assessment ID -> (pack, message template) from ``RuleId = "DG1xxx"`` findings."""
    rules: dict[str, tuple[str, str]] = {}
    for path in _source_files(root, ASSESSMENT_DIR):
        text = path.read_text(encoding="utf-8")
        pack = ASSESSMENT_PACKS.get(path.stem, path.stem)
        for match in _ASSESSMENT_RULE.finditer(text):
            message = _MESSAGE_START.search(text, match.end(), match.end() + 1200)
            template = _message_template(text, message.end(), bool(message.group("interpolated"))) if message else ""
            rules.setdefault(match.group("id"), (pack, template))
    return rules


def _message_template(text: str, start: int, interpolated: bool = True) -> str:
    """Reads a C# (interpolated) string literal body starting after its opening quote; holes become ``…``.

    Quotes inside an interpolation hole (``{string.Join(", ", xs)}``) do not end the literal.
    """
    parts: list[str] = []
    index = start
    while index < len(text):
        char = text[index]
        if char == "\\" and index + 1 < len(text):
            parts.append(text[index + 1])
            index += 2
            continue
        if not interpolated and char != '"':
            parts.append(char)
            index += 1
            continue
        if char == "{" and text.startswith("{{", index):
            parts.append("{")
            index += 2
            continue
        if char == "}" and text.startswith("}}", index):
            parts.append("}")
            index += 2
            continue
        if char == "{":
            depth = 1
            index += 1
            in_string = False
            while index < len(text) and depth:
                inner = text[index]
                if in_string:
                    if inner == "\\":
                        index += 1
                    elif inner == '"':
                        in_string = False
                elif inner == '"':
                    in_string = True
                elif inner == "{":
                    depth += 1
                elif inner == "}":
                    depth -= 1
                index += 1
            parts.append("…")
            continue
        if char == '"':
            break
        parts.append(char)
        index += 1
    return "".join(parts)


def collect_rules(root: Path) -> list[Rule]:
    """Builds the grouped rule list; raises :class:`RuleSourceError` when a catalog ID has no source."""
    titles = read_catalog_titles(root)
    classes = read_rule_classes(root)
    analyzer = read_analyzer_descriptors(root)
    assessment = read_assessment_rules(root)

    rules: dict[str, Rule] = {}
    for rule_id, (group, name, description) in classes.items():
        if rule_id == "DG001":
            continue
        rules[rule_id] = Rule(rule_id, titles.get(rule_id) or name or rule_id, description, group)

    analyzer_only = {"DG001"} | {rule_id for rule_id in analyzer if rule_id not in classes and rule_id not in titles}
    for rule_id in sorted(analyzer_only, key=_id_key):
        title, description = analyzer.get(rule_id, ("", ""))
        if rule_id not in analyzer and rule_id not in titles:
            continue
        rules[rule_id] = Rule(rule_id, titles.get(rule_id) or title or rule_id, description, "analyzer")

    for rule_id, (pack, template) in assessment.items():
        rules.setdefault(rule_id, Rule(rule_id, pack, template, "assessment"))

    missing = sorted((rule_id for rule_id in titles if rule_id not in rules), key=_id_key)
    if missing:
        raise RuleSourceError(
            "ProviderRuleCatalog.RuleTitles lists IDs with no rule class or analyzer descriptor: " + ", ".join(missing)
        )

    return sorted(rules.values(), key=lambda rule: (GROUP_ORDER.index(rule.group), _id_key(rule.rule_id)))


def render(rules: list[Rule], language: str = "en") -> str:
    """Renders the marker-delimited Markdown block for ``language`` (``en`` or ``vi``)."""
    labels = LABELS[language]
    id_header, rule_header, description_header = labels["columns"]
    lines = [START_MARKER, f"<!-- {labels['note']} -->"]
    for group in GROUP_ORDER:
        members = [rule for rule in rules if rule.group == group]
        if not members:
            continue
        lines += [
            "",
            f"### {labels['heading'][group]}",
            "",
            f"| {id_header} | {rule_header} | {description_header} |",
            "|----|------|------|",
        ]
        lines += [f"| {rule.rule_id} | {_cell(rule.title)} | {_cell(rule.description)} |" for rule in members]
    lines += ["", END_MARKER]
    return "\n".join(lines)


def extract_block(text: str) -> str | None:
    """Returns the current marker-delimited block (markers included), or None when the markers are absent."""
    start = text.find(START_MARKER)
    end = text.find(END_MARKER, start + 1) if start >= 0 else -1
    if start < 0 or end < 0:
        return None
    return text[start: end + len(END_MARKER)]


def replace_block(text: str, block: str) -> str:
    current = extract_block(text)
    if current is None:
        raise RuleSourceError(f"markers {START_MARKER} / {END_MARKER} not found")
    return text.replace(current, block, 1)


def check(root: Path, rules: list[Rule], out=sys.stdout) -> int:
    """Returns 0 when every README block matches the generated one, 1 otherwise (with a diff on ``out``)."""
    status = 0
    for language, relative in READMES.items():
        path = root / relative
        if not path.is_file():
            print(f"✗ {relative}: missing", file=out)
            status = 1
            continue
        current = extract_block(path.read_text(encoding="utf-8"))
        expected = render(rules, language)
        if current is None:
            print(f"✗ {relative}: rule-table markers not found", file=out)
            status = 1
        elif current != expected:
            print(f"✗ {relative}: rule table is out of date; run python3 scripts/gen_rule_table.py", file=out)
            out.writelines(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=f"{relative} (current)",
                    tofile=f"{relative} (generated)",
                )
            )
            status = 1
        else:
            print(f"✓ {relative}: rule table up to date", file=out)
    return status


def write(root: Path, rules: list[Rule]) -> None:
    for language, relative in READMES.items():
        path = root / relative
        text = path.read_text(encoding="utf-8")
        updated = replace_block(text, render(rules, language))
        if updated != text:
            path.write_text(updated, encoding="utf-8")
            print(f"updated {relative}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 when README.md/README.vi.md differ from the generated table")
    mode.add_argument("--print", choices=sorted(LABELS), dest="print_language", help="print the generated block")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1], help="repository root")
    args = parser.parse_args(argv)

    try:
        rules = collect_rules(args.root)
        if args.print_language:
            print(render(rules, args.print_language))
            return 0
        if args.check:
            return check(args.root, rules)
        write(args.root, rules)
        return 0
    except (RuleSourceError, OSError) as error:
        print(f"gen_rule_table: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
